trigger:
- master

resource:
- repo: self 

variables:
  tag: '$(Build.BuildId)'

pr:
- "*"


stages:
- stage: Build
  jobs:
  - job: BuildJob
    pool:
    vmImage: ubuntu-latest

    steps:
    - task: Docker@1
      displayName: 'Build the Docker image'
      inputs:
        #containerregistrytype: 'Docker Hub'
        containerRegistry: 'dockerRegistryServiceConnection'
        command: 'Build an image'
        dockerFile: '$(Build.SourcesDirectory)/Dockerfile'
        imageName: '$(ImageName)'
        #includeLatestTag: true
        #useDefaultContext: false
        buildContext: '$(Build.SourcesDirectory)/app.py'
        repository: $(DOCKER_REPOSITORY_NAME)
      env:
        DOCKER_USERNAME: $(DOCKER_USERNAME)
        DOCKER_PASSWORD: $(DOCKER_PASSWORD)

  
    #- script: |
    #    cd /flask
    #    docker build -t my-flask-app .
    #  displayName: 'Build Docker Image'
    #  continueOnError: true      

    - task: Docker@1
      displayName: 'Push the Docker image to Dockerhub'
      inputs:
        containerregistrytype: 'Docker Hub'
        containerRegistry: 'dockerRegistryServiceConnection'
        command: 'Push an image'
        imageName: '$(ImageName)'
      condition: and(succeeded(), ne(variables['Build.Reason'], 'PullRequest'))

    #steps:
    #- script: echo "Building the Docker image..."
    #  displayName: 'Building Docker Image'

    #- script: |
    #    cd /flask
    #    docker build -t my-flask-app .
    #  displayName: 'Build Docker Image'
    #  continueOnError: true  # Continue even if the build fails to allow deployment step to run

   # - task: Docker@2
   #   inputs:
   #     command: 'login'
   #     containerRegistry: 'dockerRegistryServiceConnection'  # Specify the name of your Docker registry service connection in Azure DevOps
   #   displayName: 'Login to Docker Hub'
   #   env:
   #     DOCKER_USERNAME: $(DOCKER_USERNAME)
   #    DOCKER_PASSWORD: $(DOCKER_PASSWORD)
    
   # - script: |
   #     cd flask
   #     docker tag my-flask-app shruti1402/my-flask-app:latest
   #     docker push shruti1402/my-flask-app:latest
   #   displayName: 'Push Docker Image'



