name: Run flask application 

on:
  push:
    branches: ['master']

jobs: 
  build: 
    name: flask application
    runs-on: ubuntu-latest 
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3

   #   - name: Build Docker image
   #     run: |
   #       cd flask
   #       docker build -t my-flask-app-new .
   #       docker images
   #       docker ps 

    #  - name: Log in to Docker hub
    #    uses: docker/login-action@v1
    #    with:  
    #      login-server: https://hub.docker.com/repository/docker/shruti1402/flaskapp
    #      username: ${{ secrets.DOCKER_USERNAME }}
    #      password: ${{ secrets.DOCKER_PASSWORD }}
          
#      - name: Push docker image
#        run: |
#          cd flask
#          docker tag my-flask-app-new shruti1402/my-flask-app-new:latest
#          docker push shruti1402/my-flask-app-new:latest

#      - name: Pull docker images
#        uses: appleboy/ssh-action@master
#        with:
#          host: ${{ secrets.HOST_DNS }}
#          username: ubuntu
#          key:  ${{ secrets.EC2_SSH_KEY }}
#         envs: GITHUB_ENV
#          script: |
#            sudo docker login
#            sudo docker pull shruti1402/my-flask-app-new:latest
#            sudo docker stop flask_img_new
#            sudo docker rm flask_img_new
#            sudo docker run -d --name flask_img_new -p 8000:8000 shruti1402/my-flask-app-new
      - name: check path 
        run: ls 
      - name: upload artifact
        uses: actions/upload-artifact@v3
        with:
          path: flask/Dockerfile
          
      
     # - name: Set up Python 3.7
     #   uses: actions/setup-python@v2
     #   with:
     #     python-version: 3.7
     # - name: Install dependencies
     #   run: |
           # cd /flask
     #       ls
     #       cd flask 
     #       pip install --upgrade pip
     #       python -m pip install --upgrade pip 
     #       pip install --no-cache-dir -r requirements.txt
     # - name: Configure AWS 
     #   uses: aws-actions/configure-aws-credentials@v1
     #   with:
     #     aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
     #     aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
     #     aws-region: us-east-1
     # - name: Build Application and Run unit Test
     #   run: |
     #       ls
     #       cd flask
     #       python app.py

#  deploy:
#    needs: build
#    name: Deploy to EC2 on master branc push
#    runs-on: ubuntu-latest

#    steps:
#      - name: Checkout the files
#        uses: actions/checkout@v2

#      - name: Deploy code to EC2
#        uses: easingthemes/ssh-deploy@main
#        env:
#          SSH_PRIVATE_KEY: ${{ secrets.EC2_SSH_KEY }}
#          REMOTE_HOST: ${{ secrets.HOST_DNS }}
#          REMOTE_USER: ${{ secrets.USERNAME }}
#          TARGET: ${{ secrets.TARGET_DIR }}

     

   
     
 
      
