name: Run flask application 

on:
  push:
    branches: ['master']

jobs: 
  deploy: 
    name: flask application
    runs-on: ubuntu-latest 
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3
      - name: Set up Python 3.7
        uses: actions/setup-python@v2
        with:
          python-version: 3.7
      - name: Install dependencies
        run: |
            pip install --upgrade pip
            python -m pip install --upgrade pip            
      - name: Check docker installed or not
        run: docker run hello-world
      - name: Push to docker hub
        uses: docker/build-push-action/@v1
        with:
          username: ${{secrets.DOCKER_USERNAME}}
          password: ${{secrets.DOCKER_PASSWORD}}
          repository: ${{secrets.DOCKERHUB_REPO}}
          tag_with_ref: true
